name: Neo4Ecto CI
on: [push]

jobs:
  test:
    name: linter
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.9.2-erlang-22.3.4.16-alpine-3.13.1"
          - "1.12.0-rc.1-erlang-24.0-alpine-3.13.3"

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: test elixir linters
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixir}} +setup-code-check
  test-neo4j:
    name: neo4j
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.12.0-rc.1-erlang-24.0-alpine-3.13.3"
        neo4j:
          - "neo4j:4.1"
          - "neo4j:4.2.5"
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: tests
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixir}} --build-arg NEO4J=${{matrix.neo4j}} +test-neo4ecto
