name: Neo4Ecto CI
on: [push]

jobs:
  test:
    name: linter
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        elixir:
          - "1.9.2-erlang-22.3.4.16-alpine-3.13.1"
          - "1.12.0-rc.1-erlang-24.0-alpine-3.13.3"

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: test ectl_sql
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixir}} +setup-linters
  test-neo4j:
    name: linter
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        elixir:
          - "1.9.2-erlang-22.3.4.16-alpine-3.13.1"
          - "1.12.0-rc.1-erlang-24.0-alpine-3.13.3"
        neo4j:
          - "4.1"
          - "4.2"
          - "4.2.5"
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: test ectl_sql
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixir}} +test-neo4ecto