name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      neo4j:
        image: neo4j:4.2
        ports: ["7687:7687"]
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: none
        options: >-
          --health-cmd "cypher-shell -u neo4j -p test 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-start-period 10s
          --health-retries 5
    strategy:
      matrix:
        include:
          - pair:
              elixir: 1.8.2
              otp: 20.3.8
          - pair:
              elixir: "1.12.0-rc.0"
              otp: "24.0-rc2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix test
